dist: trusty
env:
  global:
  - TFBIN_DIR=$HOME/tfbin
  - TERRAFORM_VERSION=0.11.13
install:
- "./scripts/download_terraform.sh $TERRAFORM_VERSION"
script:
- "~/tfbin/terraform fmt -write=false -diff=true -check"
notifications:
  email: false
  slack:
    secure: zMgDNT5Hb5CFltbb11wK0sig1/OfTc5jQ4ZirL0Axx8Obr2BGn3fJbJFIgImOs6hpc/3K6d9r4cAkMPlO8cEaF2PWvZQ95bpqH5Bfpa+hv65QhU+kA2yoCJjbTmwotu5nkjUyb/TNH8VBZ3Tke2XBtwSkkqmg6AmuIaB50aw8Ajegyr6gD6oaABu1XZ9jp9CrFPzl4qLUDcd+pW2b4rnAESlatuljw/Pnu0mzetq3YYYfzNyLAiEIfHql0DIbzULSSYzquycaVJN4ly1V/aEoBsln+IqtZne9x/PC3ny7FVvf60hf3YZd+2fP7TGSB9wDOSE8CS8uOyL7z9ubRip+/eJwgQopiPekwODRGtK7Ve4cjsowbQoTsJ+VJTTEc0DV3/MYtTSTT90EvyV+7LcoF6dL21SsKJiAl6hJWhLcScVk2x888BSGDaS3jzIl3T3K3805pBHGNdYmW8UZFCKKOE5WBVtycYMF2aV2/qUOZg5ChEuklaSFNwqzG4I7UKRreu/yAhANpiotk+9BqR5kSCiW1dg9Bgs8LfPax1QkQ1598A96qMECNOXklsYZ3L0OwE6HJr2sQX79RCra3FP3lO69LyGFYMBY26b4TO6iwan/Yt4EDjqqgedM5EYAQp7qS6jjdabfdKXdR1BRcMCAVPbeB4F0eK5Y0e6FL/4Xaw=
